sudo: false

language: python
python: "3.7"

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python -m unittest
  - coverage run minesweeper/tests/run_all_tests.py

after_script:
  - codecov